elevador/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('mantencion.urls')),
]

mantencion/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from .views import inicio, crearcliente,listaclientes,crearorden,success

app_name="mantencion"
urlpatterns=[
    path('',views.inicio,name='inicio'),
    path('login/', views.login,name='login'),
    path('logout/', views.logout,name='logout'),
    path('inicio/',views.inicio,name='inicio'),
    path('panel/',views.panel,name='panel'),
    path('crearcliente/',views.crearcliente,name='crearcliente'),
    path('crearorden/',views.crearorden,name='crearorden'),
    path('listaclientes/',views.listaclientes,name='listaclientes'),
    path('success/', views.success, name='success'),
]

mantencion/models.py
from django.db import models
from django.urls import reverse
import uuid

# Create your models here.

class Servicio(models.Model):
    Horaatencion=models.CharField(max_length=4)
    Fechaatencion=models.CharField(max_length=6)
    Horainicio=models.CharField(max_length=4)
    Horatermino=models.CharField(max_length=4)
    Idascensor=models.CharField(max_length=5)
    Modeloascensor=models.CharField(max_length=30)
    Falladetectada=models.CharField(max_length=100)
    Reparacionesefectuadas=models.CharField(max_length=100)
    Piezascambiadas=models.CharField(max_length=100)
    Recibetrabajo=models.CharField(max_length=100)

    def __str__(self):
        return self.Horaatencion

class Cliente(models.Model):
    nombre = models.CharField(max_length=40)
    direccion = models.CharField(max_length=70)
    ciudad = models.CharField(max_length=30)
    comuna = models.CharField(max_length=30)
    telefono = models.CharField(max_length=10)
    email = models.EmailField(max_length=50)

    def __str__(self):
        return self.nombre

class Orden(models.Model):
    folio = models.AutoField(primary_key=True)
    cliente = models.ForeignKey('Cliente',db_column='nombre', on_delete=models.CASCADE)
    fecha = models.DateField()
    horainicio = models.TimeField()
    horafin = models.TimeField()
    idascensor = models.IntegerField()
    modeloasc = models.CharField(max_length=30)
    fallas = models.CharField(max_length=200, blank=True, null=True)
    reparaciones = models.CharField(max_length=200, blank=True, null=True)
    piezascambiadas = models.CharField(max_length=100, blank=True, null=True)
    receptor = models.CharField(max_length=50)
    tecnico = models.ForeignKey('tecnico', on_delete=models.CASCADE)

class tecnico(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name

mantencion/forms.py
from django import forms

from .models import Cliente, Orden
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class ClienteForm(forms.ModelForm):

	class Meta:
		model = Cliente

		fields = [
			'nombre',
			'direccion',
			'ciudad',
			'comuna',
			'email',
			'telefono',
		]
		labels = {
			'nombre': 'Nombre',
			'direccion': 'Direccion',
			'ciudad': 'Ciudad',
			'comuna': 'Comuna',
			'email': 'Email',
			'telefono': 'Telefono',
		}
		widgets = {
			'nombre': forms.TextInput(attrs={'class':'form-control'}),
			'direccion': forms.TextInput(attrs={'class':'form-control'}),
			'ciudad': forms.TextInput(attrs={'class':'form-control'}),
			'comuna': forms.TextInput(attrs={'class':'form-control'}),
			'email': forms.TextInput(attrs={'class':'form-control','type':'email'}),
			'telefono': forms.TextInput(attrs={'class':'form-control','type':'number'}),

		}
		
class OrdenForm(forms.ModelForm):
	class Meta:

		model = Orden
		fields =[
			'cliente',
			'fecha',
			'horainicio',
			'horafin',
			'idascensor',
			'modeloasc',
			'fallas',
			'reparaciones',
			'piezascambiadas',
			'receptor',
			'tecnico',
		]
		labels = {
			'cliente': 'Cliente Asociado',
			'fecha': 'Fecha de Trabajo',
			'horainicio': 'Hora de Inicio',
			'horafin': 'Hora de Fin',
			'idascensor': 'Código de Ascensor',
			'modeloasc': 'Modelo ',
			'fallas': 'Fallas detectadas',
			'reparaciones': 'Reparaciones realizadas',
			'piezascambiadas': 'Piezas reemplazadas',
			'receptor': 'Receptor de trabajo',
			'tecnico': 'Tecnico encargado',
		}
		widgets = {
			'cliente': forms.Select(attrs={'class': 'form-control col-12 justify-content-center'	}),
			'fecha': forms.SelectDateWidget(attrs={'class':'form-control col-12 justify-content-center'}),
			'horainicio': forms.TextInput(attrs={'class':'form-control col-12 justify-content-center','type':'time'}),
			'horafin': forms.TextInput(attrs={'class':'form-control col-12 justify-content-center' ,'type':'time'}),
			'idascensor': forms.TextInput(attrs={'class':'form-control col-12 justify-content-center','type':'number'}),
			'modeloasc': forms.TextInput(attrs={'class':'form-control col-12 justify-content-center'}),
			'fallas': forms.TextInput(attrs={'class':'form-control col-12 justify-content-center' }),
			'reparaciones': forms.TextInput(attrs={'class':'form-control col-12 justify-content-center'}),
			'piezascambiadas': forms.TextInput(attrs={'class':'form-control col-12 justify-content-center'}),
			'receptor': forms.TextInput(attrs={'class':'form-control col-12 justify-content-center'}),
			'tecnico': forms.Select(attrs={'class': 'form-control col-12 justify-content-center'}),
		}

class RegistroForm(UserCreationForm):

	class Meta:
		model = User

		fields = [
				'username',
				'first_name',
				'last_name',
				'email',
			]
		help_texts={
				'username': None,
		}
		labels = {
				'username': 'Nombre de Usuario',
				'first_name': 'Nombres',
				'last_name': 'Apellidos',
				'email': 'Correo Electronico',
		}

mantencion/views.py
from django.shortcuts import render
from django.utils import timezone
from django.http import HttpResponse
from .models import Servicio,Cliente
from django.shortcuts import render, redirect
from django.contrib.auth import logout as do_logout
from django.contrib.auth import authenticate
from django.contrib.auth.forms import AuthenticationForm
from django.views.generic import CreateView
from django.contrib.auth import login as do_login
from django.contrib.auth.forms import UserCreationForm
from .forms import ClienteForm, OrdenForm
from .forms import RegistroForm
from django.urls import reverse_lazy, reverse
from django.http import HttpResponseRedirect
# Create your views here.

def inicio(request):
    return render(request, 'elev/inicio.html')

def panel(request):
    return render(request, 'elev/panel.html')

def login(request):
    # Creamos el formulario de autenticación vacío
    form = AuthenticationForm()
    if request.method == "POST":
        # Añadimos los datos recibidos al formulario
        form = AuthenticationForm(data=request.POST)
        # Si el formulario es válido...
        if form.is_valid():
            # Recuperamos las credenciales validadas
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            # Verificamos las credenciales del usuario
            user = authenticate(username=username, password=password)

            # Si existe un usuario con ese nombre y contraseña
            if user is not None:
                # Hacemos el login manualmente
                do_login(request, user)
                # Y le redireccionamos a la portada
                return redirect('/')

    # Si llegamos al final renderizamos el formulario
    return render(request, "elev/login.html", {'form': form})

def listaclientes(request):
    cliente = Cliente.objects.all()
    contexto = {'clientes':cliente}
    return render(request, 'elev/listaclientes.html',contexto)

def crearcliente(request):
    if request.method =='POST':
        form = ClienteForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect('mantencion:success')
    else:
        form = ClienteForm()

        return render(request,'elev/crearcliente.html',{'form':form})

def crearorden(request):
    if request.method =='POST':
        form = OrdenForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect('mantencion:success')
    else:
        form = OrdenForm()

        return render(request,'elev/crearorden.html',{'form':form})

def success(request):
    return render(request,'elev/success.html')

def logout(request):
    # Finalizamos la sesión
    do_logout(request)
    # Redireccionamos a la portada
    return redirect('/')

mantencion/templates/elev/base_generic.html
{% load static %}
<!DOCTYPE html>
<html lang="ES">
<head>
    <title>FixElevator</title>
    <meta charset="UTF-8"/>
    
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" type="text/css">
    <script src="{% static 'js/comunas.js'%}"></script>
    <link rel="stylesheet" href="{% static 'css/estilos.css' %}" type="text/css">
</head>

<body>
<header>
    <div class="header">
        <div class="row">      
            <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12"><h1 class="text-center" style="color: rgb(51, 8, 206);">FixElevator</h1></div>
            <div class="col-12 col-sm-12 col-md-12 col-lg-2 col-xl-2"><a href="{% url 'mantencion:inicio' %}"><h3 class="text-center" style="color: rgb(240, 255, 250);">Inicio</h2></a></div>
            <div class="col-12 col-sm-12 col-md-12 col-lg-2 col-xl-2"><a href="{% url 'mantencion:login' %}"><h3 class="text-center" style="color: azure;">Ingresar</h2></a></div>
            {% if user.is_authenticated %}
            <div class="col-12 col-sm-12 col-md-12 col-lg-2 col-xl-2"><a href="{% url 'mantencion:crearcliente' %}"><h3 class="text-center" style="color: azure;">Crear Cliente</h2></a></div>
            {% endif %}
            {% if user.is_authenticated %}
            <div class="col-12 col-sm-12 col-md-12 col-lg-2 col-xl-2"><a href="{% url 'mantencion:crearorden' %}"><h3 class="text-center" style="color: azure;">Crear Orden</h2></a></div>
            {% endif %}
            {% if user.is_authenticated %}
            <div class="col-12 col-sm-12 col-md-12 col-lg-2 col-xl-2"><a href="{% url 'mantencion:listaclientes' %}"><h3 class="text-center" style="color: azure;">Lista Clientes</h2></a></div>
            {% endif %}
            {% if user.is_authenticated %}
            <div class="col-12 col-sm-12 col-md-12 col-lg-2 col-xl-2"><a href="/logout"><h3 class="text-center" style="color: azure;">Salir</h2></a></div>
            {% endif %}
        </div>
    </div>
</header>
    {% block content %}
    {% endblock %}
<footer>
    <div class="container" >
        <div class="row">
            <div class="col-4">
                <h5 class="text-left">Contacto</h5>
                    <img src="{% static 'img/facebookicon.jpg' %}" alt="Facebook" width="30" height="30"  >
                    <img src="{% static 'img/twitericon.jpg' %}"  alt="Twitter" width="30" height="30" > 
                    <img src="{% static 'img/instagramicon.jpg' %}"  alt="Instagram" width="30" height="30" >
                    <img src="{% static 'img/giticon.jpg' %}" alt="GitHub" width="30" height="30" >
            </div>
            <div class="col-4"> 
                <h5 class="text-center">Copyright © 2019-2019 Elevador Todos los derechos reservados.</h5>
            </div>
            <div class="col-4">
                <h5 class="text-right">Ubicación</h5>
                <h5 class="text-right">Esq Blanca 501, Maipú, Región Metropolitana</h5>
            </div>
        </div>
    </div>
</footer>
</body>
</html>

mantencion/templates/elev/crearcliente.html
{% extends 'elev/base_generic.html' %}
{% load static %}
{% block content %}

<div class="container">
  <br>
  <h3 class="text-center" style="color: rgb(255, 255, 255);"> Registro de Clientes</h3>
  <br>
  <div class="row">
    <div class="col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6">
      <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn">Guardar</button>
      </form>
    </div>
  </div>
</div>
<br><br><br><br><br>
{% endblock %}

mantencion/templates/elev/crearorden.html
{% extends 'elev/base_generic.html' %}
{% load static %}
{% block content %}

<div class="container">
  <br>
  <h3 class="text-center" style="color: rgb(255, 255, 255);"> Crear Orden de Servicio</h3>
  <br>
  <div class="row">
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" class="btn">Guardar</button>
    </form>
  </div>
</div>
<br><br><br><br><br><br>

{% endblock %}

mantencion/templates/elev/inicio.html
{% extends 'elev/base_generic.html' %}
{% load static %}
{% block content %}
<br>
<div class="container">
    <div class="col-sm-12">
        <div class="text-center">
            <h3 style="color: rgb(0, 0, 0);;">Bienvenido</h3>
        </div>
    </div>
    
    <br>
    <div class="row">
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 col-xl-6">
            <img src="{% static 'img/ele.jpg' %}" alt="Elevador" style="width:100%;">
        </div>  
        <br>              
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 col-xl-6">
            <div class="text-center">
                <h4 style="color: rgb(0, 0, 0);">Quienes Somos</h4>
                <p class="esp" style="color: rgb(0, 0, 0);" ALIGN="justify" >
                    Somos FixElevator, una empresa con el estándar de calidad mas alto para la mantención, 
                    reparación, modernización y modeificacion de ascensores en edificios residenciales, 
                    públicos, comerciales y entre otros, entregando soluciones óptimas y asesorías 
                    especializadas según los requerimientos del mercado.

                    Cuentamos con profesionales altamente capacitados y con una vasta trayectoria 
                    en empresas del rubro, lo cual nos permite interactuar con cualquier proyecto ya 
                    sea de mantención, reparación, modernización o modificacion y contando con el certificacion 
                    de nuestra Matriz Europea y sus distintas subsidiarias de alrededor del Mundo.
                </p><br>
            </div>
        </div>
    </div>
    <br>
</div>
<br><br><br><br><br>

{% endblock %}

mantencion/templates/elev/listaclientes.html
{% extends 'elev/base_generic.html' %}
{% load static %}
{% block content %}

<div class="container">
	<br>
	<h3 class="text-center" style="color: rgb(255, 255, 255);">Lista de Clientes</h3>
	<br>
	<div class="row">
		<aside>
			<div class="hola">
				<table class=table table-bordered>
					<thead>
						<tr>
							<td>#</td>
							<td>Nombre</td>
							<td>Direccion</td>
							<td>Ciudad</td>
							<td>Comuna</td>
							<td>Telefono</td>
							<td>Email</td>
						</tr>
					</thead>
						<tbody>
							{% if clientes %}
							{% for cliente in clientes %}
								<tr>
									<td>{{ cliente.id }}</td>
									<td>{{ cliente.nombre }}</td>
									<td>{{ cliente.direccion }}</td>
									<td>{{ cliente.ciudad }}</td>
									<td>{{ cliente.comuna }}</td>
									<td>{{ cliente.telefono }}</td>
									<td>{{ cliente.email }}</td>
								</tr>
									{% endfor %}
									{% else %}
										<h1> No hay registros de clientes</h1>
									{% endif %}
						</tbody>
			</div>
		</aside>
		
	</div>
</div>

{% endblock %}

mantencion/templates/elev/login.html
{% extends 'elev/base_generic.html' %}
{% load static %}
{% block content %}
<br>
<div class="container">
    <h2 style="color: rgb(255, 255, 255);">Iniciar Sesion</h2>
        <form method="POST">
            {{ form.as_p }}
            {% csrf_token %}
        <button type="submit">Login</button>
        <br>
        </form>
    <hr />
</div>
{% endblock %}

mantencion/templates/elev/success.html
{% extends 'elev/base_generic.html' %}
{% load static %}
{% block content %}

<div class="container">
    <br><br><br><br><br>
    <h3 class="text-center" style="color: rgb(46, 238, 8);">Operación ejecutada con exito!</h3>
</div>

<br><br><br><br><br><br><br>

{% endblock %}